# 服务器端口
server:
  port: 8080
  servlet:
    context-path: /    # 基础路径

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health  # 只监控info 和 health

info:
  app.name: $artifactId$
  app.description: $description$
  app.version:  $parent.version$


spring:
  application:
    name: admin-application
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  profiles:
    include: common,db  # 引入公共的配置文件
    active: dev      # 当前启用 dev 配置