# 服务器端口
server:
  port: 8080
  servlet:
    context-path: /    # 基础路径


spring:
  application:
    name: admin-application

  profiles:
    include: common,db  # 引入公共的配置文件, 加载application-common.yml 里面的配置
    active: dev      # 当前启用 dev 配置, 加载application-dev.yml 里面的配置