# 服务器端口
server:
  port: 8088
  servlet:
    context-path: /    # 基础路径

# 监控信息
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health  # 只监控info 和 health

# info 信息
info:
  app.name: $artifactId$
  app.description: $description$
  app.version: $version$
  env.java_version: $java.version$
  env.springBoot_version: $spring-boot.version$

# 加载配置
spring:
  application:
    name: admin-application


  profiles:
    # 引入公共的配置文件
    include: common,db

    # 当前启用 dev 配置
    active: dev


decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-format: "sql_execution_time:[%(executionTime)ms]: {[%(category)],[connection%(connectionId)]}\n\n %(sql) \n"

#decorator:
#  datasource:
#    datasource-proxy:
#      multiline: true
#      json-format: true
#      count-query: true
#      # 查询
#      query:
#        enable-logging: true
#        log-level: warn
#        logger-name: query.log
#
#      # 慢查询
#      slow-query:
#        enable-logging: true
#        log-level: warn
#        threshold: 300
#        logger-name: slow-query.log
