# 配置日志文件
logging:
  level:
    #  TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    web: TRACE

# 开发环境,数据库连接地址
mysql:
  url: localhost
  username: ENC(ph4c3mIv72TbbyUfzYT2xA==)
  password: ENC(ZjvQItwSkF6nX23LQfEYOg==)